# fly.toml file generated for clutch-planet-web on 2023-06-30T11:51:17-03:00

app = "clutch-planet-web"
primary_region = "scl"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
